api_version = "2024-01"

[[extensions]]
type = "cart_transform"
name = "custom-variant-pricing"
handle = "custom-variant-pricing"

[extensions.input]
variables = {}

[extensions.build]
command = ""
path = "dist/main.wasm"
